name: main

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - run: mvn test-compile
      - run: tar -cvzf targets.tar.gz core/target/**/* jts/target/**/*
      - name: "Upload targets"
        uses: actions/upload-artifact@v2
        with:
          name: targets
          path: targets.tar.gz
          if-no-files-found: error
          retention-days: 1

  verify:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - name: Download targets
        uses: actions/download-artifact@v2
        with:
          name: targets
      - run: tar -xvzf targets.tar.gz
      - run: mvn verify
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure() # run this step even if previous step failed
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit tests
          path: "**/*/target/surefire-reports/*.xml"
          reporter: java-junit

  tag:
    runs-on: ubuntu-latest
    needs: verify
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Claculate next version
        id: next-tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DRY_RUN: true
          DEFAULT_BUMP: patch
          WITH_V: false
      - name: Claculate next version
        id: next-tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DRY_RUN: true
          DEFAULT_BUMP: patch
          WITH_V: false


  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}", "password": "${{ secrets.SONATYPE_PASSWORD }}" }]'
