name: main

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SONATYPE_USERNAME # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - run: gpg --list-secret-keys --keyid-format=long
      - run: mvn test-compile
      - run: tar -cvzf targets.tar.gz core/target/**/* jts/target/**/*
      - name: "Upload targets"
        uses: actions/upload-artifact@v2
        with:
          name: targets
          path: targets.tar.gz
          if-no-files-found: error
          retention-days: 1
      - run: mvn -X verify
      - name: Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1.5.0
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit tests
          path: "**/*/target/surefire-reports/*.xml"
          reporter: java-junit

  release:
    runs-on: ubuntu-latest
    needs: verify
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: SONATYPE_USERNAME # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - name: Download targets
        uses: actions/download-artifact@v2
        with:
          name: targets
      - run: tar -xvzf targets.tar.gz
      - run: mvn release:clean release:prepare --batch-mode
      - run: mvn release:perform
