name: main

on:
  push:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - run: mvn dependency:resolve

  compile:
    needs: update_dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - run: mvn compile
      - run: mvn test-compile
      - name: Store targets
        uses: alehechka/upload-tartifact@v1
        with:
          name: targets
          path: |
            **/*/target/**/*
          if-no-files-found: error
          retention-days: 1
  unit_test:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-dependencies-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-dependencies-${{ runner.os }}-
      - name: Download targets
        uses: alehechka/download-tartifact@v1
        with:
          name: targets
      - run: mvn test
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure() # run this step even if previous step failed
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit tests
          path: "**/*/target/surefire-reports/*.xml"
          reporter: java-junit
